### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by aAXEe** [aAXEe/online_chart_ol3#1]
My favorite is [BSD-3-Clause](https://opensource.org/licenses/BSD-3-Clause).

What do think?

**Comment by mojoaxel** [comment]
I'm more a friend of "old-school" OpenSource licenses. I belive in "copyleft": You can use my code but if you improve it you have to publich the improvment!
Therefor my favorite license is the [AGPL](http://www.gnu.org/licenses/why-affero-gpl.de.html) for WebApps.

As far as I can see the most other OSM projects also use a GPL license:
* [JOSM](https://github.com/openstreetmap/josm/blob/mirror/LICENSE)
* [openstreetmap-website](https://github.com/openstreetmap/openstreetmap-website/blob/master/LICENSE)
* [mkgmap](https://github.com/openstreetmap/mkgmap/blob/master/LICENCE)
* [beboj](https://github.com/openstreetmap/beboj/blob/master/LICENSE)
* [OSMembrane](https://github.com/openstreetmap/OSMembrane/blob/master/LICENSE.txt)

**Comment by aAXEe** [comment]
After some discussions about the pro and cons of copyleft and its use to this software, I agree to use the [AGPL](http://www.gnu.org/licenses/agpl-3.0).

The template for use in all source files:
```
OpenSeaMap chart framework - an interative online chart.
Copyright (C) <year(s)>  <your name here>

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as
published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
```

---

- [ ] Add http://www.gnu.org/licenses/agpl-3.0.txt as license text

- [ ] Add copyright note and license to all existing files

- [ ] Add automatic source tarball in release builds

- [ ] Add link to github and source tarball in website

**Comment by mojoaxel** [comment]
With #31 the following license-banner is generated an added on top of each js-module before deployment:

```
/*!
 * osm-map-ol3@0.0.1 - OpenSeaMap charting framework
 * 
 * Copyright (c) 2015-2016 by 
 * 	Axel Utech <axel@brasshack.de> (https://github.com/aAXEe)
 * 	Alexander Wunschik <alex@wunschik.net> (https://github.com/mojoaxel)
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/agpl.txt>.
 * 
 * The sources can be found here:
 * github:aAXEe/online_chart_ol3
 */
```
