### ISSUE TITLE
Layer: Luftbild

### ISSUE THREAD

**Issue by mojoaxel** [aAXEe/online_chart_ol3#11]

**Comment by Nautic** [comment]
Vor etwa drei Jahren kam auf der "boot" der Wunsch von den Mappern, Basiskarte und Luftbild kontinuierlich überlagern zu können (mit Slider und Transparenz).

Diese Funktion ist ein Werkzeg für Mapper:
Damit kann man sehr schnell und intuitiv den aktuellen Datenbestand mit dem Luftbild vergleichen/prüfen, und fehlende/abweichende Stellen mit JOSM-Remote korrigieren.
Einschaltbar im Menü "Werkzeuge".

Damit nicht immer beide Layer doppelt geladen werden müssen (weil aus Bequemlichkeit diese Funktion immer eingeschalten bleibt), sollte der Slider nicht in den Cookies gespeichert werden, sondern immer wieder neu eingeschaltet werden müssen.
