### ISSUE TITLE
Layer: Marine Traffic

### ISSUE THREAD

**Issue by mojoaxel** [aAXEe/online_chart_ol3#16]

**Comment by aAXEe** [comment]
At the old map we use data from http://www.marinetraffic.com/ . The old API does not work anymore.
See also http://forum.openseamap.org/viewtopic.php?id=2188

**Comment by Nautic** [comment]
Wir sollen eine missbrauch-sichere Schnittstelle zur verfügung stellen,
dann klappt alles wie gehabt.

**Comment by aAXEe** [comment]
If we have API access (creadits), we can display the traffic data (see #103).
