### ISSUE TITLE
MediWest chart download link does not work

### ISSUE THREAD

**Issue by Alomphega** [aAXEe/online_chart_ol3#203]
Hi, 
As the title says, when I tried to download the Mediterranean chart, the
"ftp://ftp5.gwdg.de/pub/misc/openstreetmap/openseamap/chartbundles/kap/OSM-OpenCPN-KAP-MediWest.7z" 
link failed (I tried this since few weeks with the same result before telling it here).
Hope this helps,
Cordially,
Guy

**Comment by aAXEe** [comment]
Thanks for your report!

This is a problem with the meta data provided forthis file.
See our forum for details and help: https://forum.openseamap.org/viewtopic.php?pid=4162#p4162

**Comment by Alomphega** [comment]
Thanks for your answer, but as I have already found the solution by myself,
my message was just to report it for you and let you correct this
problem...
Well, since 2 years it was not done, so I guess there is nobody able to
make the correction on the website link :-/

Anyway, thanks again ! :)

Cordially,
Guy Capra
_________________________________________________________
www.alomphega.com www.nauticaerium.com www.conceptarum.com
Sauf mention contraire explicite, ce mél est strictement confidentiel.

2017-04-23 20:03 GMT+02:00 aAXEe <notifications@github.com>:
