### ISSUE TITLE
Download MediEast Map Error

### ISSUE THREAD

**Issue by lukpecyn** [aAXEe/online_chart_ol3#204]
I cannot dowload MediEast Map. I get an error "550 Failed to change directory".
Broken link: ftp://ftp5.gwdg.de/pub/misc/openstreetmap/openseamap/chartbundles/kap/OSM-OpenCPN-KAP-MediEast.7z

**Comment by aAXEe** [comment]
This is a problem with the meta data provided forthis file.
See our forum for details and help: https://forum.openseamap.org/viewtopic.php?pid=4162#p4162
