### ISSUE TITLE
MediEast map - OpenCPN (KAP) - link broken

### ISSUE THREAD

**Issue by radicsgabor** [aAXEe/online_chart_ol3#219]
Download link broken at: ftp://ftp5.gwdg.de/pub/misc/openstreetmap/openseamap/chartbundles/kap/OSM-OpenCPN-KAP-MediEast.7z

**Comment by aAXEe** [comment]
This is a problem with the data backend.
See also: https://forum.openseamap.org/viewtopic.php?pid=4162#p4162

The correct download link: ftp://ftp5.gwdg.de/pub/misc/openstreetmap/openseamap/chartbundles/kap/OSM-OpenCPN-KAP2-MediEast-20170115-1856.7z

**Comment by Nautic** [comment]
[All KAP-charts you can find here.](https://wiki.openstreetmap.org/wiki/KAP-charts_from_OpenSeaMap)
