### ISSUE TITLE
MediWest map link is broken

### ISSUE THREAD

**Issue by chewlius** [aAXEe/online_chart_ol3#221]
Is there also an alternative link to download the MediWest Map package?

Thank you in advance!

Best,
Julius

**Comment by omar3145** [comment]
The correct link is:
MediWest: ftp://ftp5.gwdg.de/pub/misc/openstreetm … 18-0958.7z

**Comment by chewlius** [comment]
Thank you!
ftp://ftp5.gwdg.de/pub/misc/openstreetmap/openseamap/chartbundles/kap/OSM-OpenCPN-KAP2-MediWest-20170118-0958.7z

**Comment by Nautic** [comment]
[You can find all KAP-charts here.](https://wiki.openstreetmap.org/wiki/KAP-charts_from_OpenSeaMap)
