### ISSUE TITLE
Help / Online Documentation

### ISSUE THREAD

**Issue by mojoaxel** [aAXEe/online_chart_ol3#25]
Show online documentation for each individual tool and layer (if needed).

**Comment by Nautic** [comment]
Da wäre ein [Link zum Wiki](http://wiki.openseamap.org/wiki/OpenSeaMap-dev:De:Documentation_and_Communication#Hilfe-Seiten) sinnvoll.

**Comment by aAXEe** [comment]
Each layer can display a short help/configuration via the `additionalSetup` property and an induvidual sidebar-tab via the `additionalTab`.
Interactive layers already show a message for the user.
