### ISSUE TITLE
Show Lat Long Info

### ISSUE THREAD

**Issue by windsmiths** [aAXEe/online_chart_ol3#259]
Apologies if Im missing something but would be helpful to show the cursor location in lat long or at least to include lat long of the node when showing tag information (plus the node ID)

**Comment by Nautic** [comment]
You can see the cursors coordinate in the right bottom corner in the nautical format:
N/S gg°mm.mmm' E/W ggg°mm.mmm' (1.852m or better)

**Comment by windsmiths** [comment]
Apologies - I was looking at the map2.openseamap.org
