### ISSUE TITLE
Search by location

### ISSUE THREAD

**Issue by mojoaxel** [aAXEe/online_chart_ol3#26]
Sow a search-bar for searching for locations/tags.

**Comment by Nautic** [comment]
Die Häfen aus der Hafen-DB sollte ebenfalls gefunden und prominent gelistet werden.

**Comment by Nautic** [comment]
Die Suche liefert einen oder eine Liste mehrerer Treffer.
Der ausgewählte Treffer soll auf der Karte mit einem roten Kreis angezeigt werden.,
damit man den Ort beim Verschieben/Zoomen der Karte immer sehen kann.

**Comment by aAXEe** [comment]
Implemented in #75

Some features like position (viewport) agnostic search and poi search can be added later on.

Please open new issues for detailed change requests.
