### ISSUE TITLE
Permalink/Bookmark

### ISSUE THREAD

**Issue by mojoaxel** [aAXEe/online_chart_ol3#44]
It should be possible to bookmark the active view with the given settings and export/share a permalink to the application state.

**Comment by mojoaxel** [comment]
see https://github.com/OpenSeaMap/online_chart/blob/master/javascript/permalink.js#L91 for the ol2 layers-string.

**Comment by aAXEe** [comment]
The old layer numbers are written here: https://github.com/OpenSeaMap/online_chart/blob/master/index.php#L72

**Comment by mojoaxel** [comment]
@aAXEe thx!

**Comment by Nautic** [comment]
Kann man hier https://github.com/OpenSeaMap/online_chart/blob/master/index.php#L72 ab Zeile 158 die Cookies so auslesen, dass folgende Layer beim Neustart immer auf "true" stehen:
- Basiskarte
- Koordinatengitter
- Seezeichen
- Häfen und Marinas
Unser OpenSeaMap Look-and-Feel :-)

Ausnahmen sollen nur im Einzelfall händisch über "Ansicht" möglich sein.

Bis jetzt gab es noch keine Beschwerden, dass wir zu oft Daten von Dritten ziehen (AIS, Pegel, Luftbilder, etc) - aber vielleicht müssten wir die irgendwann mal aus den Cookies entfernen, damit der Traffic nicht aus Unachtsamkeit zu gross wird.

Gibt es eigentlich einen Mechanismus der verhindert, dass der Seezeichen-Layer oder der Hafen-Layer einzeln gezogen wird? (ich fände nicht so toll, wenn "Fremdanbieter" sich damit schmücken ;-) )

**Comment by mojoaxel** [comment]
>  folgende Layer beim Neustart immer auf "true" stehen:

Bisher gibt es in der jetzigen Implementierung keine Cookies. Das würde ich auch gerne so beibehalten. Bisher werden also beim Aufruf der Applikation immer die Standart-Layer angezeigt. Welche das sein sollen sollte in #19 noch dokumentiert werden!

Wenn man die Applikation allerdings über einen Permalink aufruft werden natürlich die Layer aktiviert die dort angegeben sind. Da wird nichts zurückgesetzt.

Es wäre denkbar (z.B. im "LocalStorage") den lokalen "State" der Applikation zu speichern. Öffnet der Benutzer dann die WebApp in gleichen Browser erneut sind z.B. Position sowie die ausgewählten Layer gespeichert. Wenn das gewünscht ist sollte dazu ein neues Issue angelegt werden.

> Gibt es eigentlich einen Mechanismus der verhindert, dass der Seezeichen-Layer oder der Hafen-Layer einzeln gezogen wird?

Ich habe dazu mal ein neues Issue #51 aufgemacht. Wir sollten das dort diskutieren.
