### ISSUE TITLE
Layerspecific legend

### ISSUE THREAD

**Issue by mojoaxel** [aAXEe/online_chart_ol3#45]
It should be possible for a layer to provide a legend to explain the shown map-symbols and colors.

**Comment by Nautic** [comment]
Farb-Skala für:
- Wind: Geschwindigkeit (Bft, km/h)
- Kayak: Schwierigkeitsstufe
- Wassertiefen-Tracks: Tiefe (in Abhängigkeit der Auflösung)
- HeatMap: Ampelfarben und Farbstufen

**Comment by aAXEe** [comment]
With #66 it is possible to display a short message eg. a color scale directly an the layer config tab or add an additional tab with more information.
The layer attribution provided by openlayers is demonstrated in https://github.com/aAXEe/online_chart_ol3/commit/277ebea0278db3f6f0c1c1567c2919c78a2f843f
