### ISSUE TITLE
Coordinate grid

### ISSUE THREAD

**Issue by Nautic** [aAXEe/online_chart_ol3#47]
Kann man das Koordinatengitter direkt in die Basiskarte rendern?
https://github.com/OpenSeaMap/online_chart/blob/master/javascript/grid_wgs.js

Das hätte folgende Vorteile:
1. Drittanbieter bräuchten sich nicht um das Koordinatengitter kümmern,
egl, ob sie die Basiskarte selber rendern oder von uns beziehen.
2. Das Koordinatengitter ist (neben den Seezeichen und Häfen) unser Markenzeichen. Es wäre dann zuverlässig immer sichtbar.
3. Die Wahrscheinlichkeit sinkt, dass jemand unsere Basiskarte zweckentfremdet 
(unsere OSM-Karte für nicht-OpenSeaMap-Zwecke von unserem Server lädt),
weil er als Nicht-Seemann mit dem "störenden" Koordinatengitter nicht viel anfangen kann.
4. Wenn jemand unsere Basiskarte "klaut" wäre das unmittelbar erkennbar.
5. Wir bräuchten einen Layer weniger.

**Comment by mojoaxel** [comment]
Hätte aber auch folgende Nachteile:
* Jemand muss den Renderer entsprechend anpassen/erweitern.
* Es wäre nicht mehr möglich das Gitter auszublenden, falls man dies aus irgendeinem Grund tun möchte (z.B. Wetterkarte?)
* Das Gitter wär damit nur noch auf dem OpenStreetMap-Layer sichtbar. Nicht aber auf anderen Base-Layern wie Luftbild oder anderen speziellen Base-Layern (Nachtsicht)
* Overlays wie Höhenprofile würden das Gitter dann überdecken.

Falls Zweckentfremdung der Karten ein Problem ist kann man sich hierzu was anderes einfallen lassen.

**Comment by Nautic** [comment]
Das Koordinatengitter ist Bestandteil der Seekarte.
- Nachtsicht: Gitter erwünscht
- Wetterkarte: Gitter erwünscht
- Luftbild: Gitter erwünscht (müsste man hier irgendwie drüberlegen)

Das Koordinatengitter besteht aus den Koordinatenlinien und der Beschriftung am Kartenrand.
Die Linien lassen sich in die Kacheln der Basikarten rendern.
Die Beschriftung am Rand (links und oben) funktioniert vermutlich nur als Overlay?

Höhenprofil überdeckt das Koordiantengitter nicht:
http://map.openseamap.org/index.php?lang=de&zoom=15&lat=47.14172&lon=11.84194&layers=BFTFFFTFFTF0FFFFFFTTTF

**Comment by aAXEe** [comment]
Das Gitter ist jetzt als Overlay integriert. (vergleichbar mit der Lösung in OL2)
Eine direkte Integration in die Tiles hat mit diesem Projekt nichts unmittelbar zu tun.
