### ISSUE TITLE
Toggle full-screen

### ISSUE THREAD

**Issue by Nautic** [aAXEe/online_chart_ol3#50]
Der Schalter für Fullscreen öffnet die Karte nur "beinahe" fullscreen (Rand 1-2cm).
Nach Schliessen mit ESC bleibt diese "beinahe FS-Darstellung" auch für Windows-Desktop etc.
(Win 8.1, FF)

**Comment by aAXEe** [comment]
@Nautic: ist das inzwischen behoben?
Es hat sich einiges an dem System getan. Bei mir funktioniert der Fullscreen Modus
