### ISSUE TITLE
Dynamic layer/feature concept

### ISSUE THREAD

**Issue by mojoaxel** [aAXEe/online_chart_ol3#52]
We need a solid layer/feature concept:
- [x] Specific layers can be switched on/off.
- [x] Layers are separated in the UI between base-Layers (e.g. osm) and overlays (e.g. sea-signs).
- [x] A layer can provide his own sidebar feature/tab (e.g. tag/wiki details, legend). (#41)
- [x] A layer can provide his own controls (e.g. scale) and attribution. (#27)

**Comment by aAXEe** [comment]
Complete?

**Comment by mojoaxel** [comment]
I really would like to add custom controls (like a color/depth-scale) to the controls-panel as part of a new "feature". At the moment it is possible to add (custom) controls to the MetaControl like done in [Map.js#L152-L177](aAXEe/online_chart_ol3/blob/master/src/javascripts/Map.js#L152-L177). 
It would be nicer to add custom controls (e.g. a special scale or a custom zoom contzrol) by defining it as part of a feature. At the moment all controls must be defined in Map.js hat is very centralized.

To make clear what I want: For example the natic scale makes not much sense if no nautic layer is active. I would prefer to define the natic scale as part of every seamark layer. Than it only would be shown, if at least one nautic layer is active. If e.g. only the openstreetmap base layer and the wikipedia layer is active the nautic scale would not be shown. The same makes of corse more sense for real custom controls like depth-scales or all the weather stuff.
