### ISSUE TITLE
replace url-routing with react-router implementation

### ISSUE THREAD

**Issue by mojoaxel** [aAXEe/online_chart_ol3#53]
we should use a solid routing library instead of implementing out own routing!?

**Comment by Nautic** [comment]
Betrifft das Routing Schiffe? oder Autos? oder etwas ganz anderes?

**Comment by mojoaxel** [comment]
@nautic ;-) es geht nur darum wie intern Änderungen an der URL behandelt werden. Reine Frage der Implementierung. Für Benutzer keine Änderung.

**Comment by aAXEe** [comment]
Currently we use [uniloc](http://unicornstandard.com/packages/uniloc.html):
https://github.com/aAXEe/online_chart_ol3/blob/master/src/javascripts/store/urlHashHandling.js#L5

It is not react-router but it works and is simple, isn't it?

**Comment by mojoaxel** [comment]
You are right. Why not keep uniloc!?
